Add mllint in pr-validation pipeline.

diff --git a/.github/workflows/pr-validation.yml b/.github/workflows/pr-validation.yml
--- a/.github/workflows/pr-validation.yml
+++ b/.github/workflows/pr-validation.yml
@@ -38,4 +38,9 @@ jobs:
         run: |
           set -e # fail on error
           poetry run pylint -j --fail-under=10.0 src
+      
+      - name: Run mllint
+        run: |
+          set -e # fail on error
+          poetry run mllint
         
